[WCNCR00213373] misc: Fix nicEventAssertDump() build fail
[Description]
Fix nicEventAssertDump() build fail

Symptom:
Get build error with invalid usage of strncpy()
os/linux/include/gl_kal.h:847:44: error: ‘strncpy’ specified bound
depends on the length of the source argument [-Werror=stringop-overflow=]
    kalStrnCpy(&aucVersionBuf[1],
    ^~~~~~~~~~

Solution:
* Add new macro kalStrnCat(des, src, n)
* Refactor log-handling process

MTK-Commit-Id: 598eee081a98a5a158e9601dcf8569770a1f87f2

Change-Id: I981037ecffb7c52a3f63997097ea72d297e79031
Signed-off-by: Deren Wu <deren.wu@mediatek.com>
CR-Id: WCNCR00213373
Feature: misc
Reviewed-on: http://gerrit.mediatek.inc:8080/c/neptune/wlan_driver/gen4m/+/3689723
Tested-by: Xinguo Cheng <xinguo.cheng@mediatek.com>
CheckCourse: srv_hbgsm001 <srv_hbgsm001@mediatek.com>
CheckPatch: srv_hbgsm001 <srv_hbgsm001@mediatek.com>
CheckPatch: Check Patch <srv_checkpatch@mediatek.com>
Reviewed-by: Xinguo Cheng <xinguo.cheng@mediatek.com>
Reviewed-by: Ming-Pei Chen <ming-pei.chen@mediatek.com>
Build: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Test: srv_mspautosanity
(cherry picked from commit f2120449d4a86951eceb65d06be024c73dc1a828)
Reviewed-on: https://gerrit.mediatek.inc/c/neptune/wlan_driver/gen4m/+/5676249
CheckCourse: srv_pis <srv_pis@mediatek.com>
CheckCRInfo: srv_pis <srv_pis@mediatek.com>
CheckForbiddenKeyword: srv_pis <srv_pis@mediatek.com>
CheckPatch: srv_pis <srv_pis@mediatek.com>
Build: srv_preflight_a001 <srv_preflight_a001@mediatek.com>
Reviewed-by: desmond.lin <desmond.lin@mediatek.com>
Reviewed-by: ben.lai <ben.lai@mediatek.com>