[WCNCR00152844] misc: Fix compile error if IPV6 is enabled as module
[Description]
Fix build error when IPV6 is enabled as module in kernel config:
    os/linux/gl_kal.c: In function kalGetIPv6Address:
    os/linux/gl_kal.c:4448:41: error: dereferencing pointer to
    incomplete type struct inet6_ifaddr

Test build ok with following Linux kernel versions:
3.10, 3.13, 3.18, 4.4

MTK-Commit-Id: 0190d2f5aa2be556d15bd164b9083990dc237359

Feature: misc
Change-Id: Ib79024db410d9e4160a525e4ff89509da018bcb1
Signed-off-by: George Kuo <george.kuo@mediatek.com>
CR-Id: WCNCR00152844
(cherry picked from commit f7f892c28e1e5fdc250dfa8e749599611c775579)