[WCNCR00145892] regd: Fix vndr get chnl build err
[Description]

build error beacause of change id I0703ffeefb722fb6c29bf5d672562255e385c511
softap: add BW/SCO/S0/S1 config from cfg80211

CC [M]  /proj/mtk09509/repo_upload_ce/wlan_driver
/gen4m/os/linux/gl_p2p_kal.o
/proj/mtk09509/repo_upload_ce/wlan_driver/gen4m/
os/linux/gl_vendor.c: In function
‘mtk_cfg80211_vendor_get_channel_list’:
/proj/mtk09509/repo_upload_ce/wlan_driver/gen4m/
os/linux/gl_vendor.c:819:2: error:
the frame size of 1104 bytes is larger
than 1024 bytes [-Werror=frame-larger-than=]
  }

reduce ChannelList from 64 to
MAX_CHN_NUM 39 to fix this build error

MTK-Commit-Id: ec96941602afaeddc0e04dc75c03d721f338e0c7

Change-Id: I1dd146ddf6a33defe1e553f772399b45ac81f5ca
Feature: regd
Signed-off-by: Litien Chang <litien.chang@mediatek.com>
CR-Id: WCNCR00145892
(cherry picked from commit 8e44c85ebb5790ec42331e96bb64dc570c316315)