[WCNCR00179831] misc: Fix build error on kernel 3.14
[Description]
Fix build error on kernel 3.14

Build fail with following error message

os/linux/gl_init.c: In function ‘wlanCreateWirelessDevice’:
os/linux/gl_init.c:1798:9: error: ‘struct wiphy’
		has no member named ‘max_num_csa_counters’
  prWiphy->max_num_csa_counters = 2;

MTK-Commit-Id: cef6ba4e6e427f350a01450c3bf0b3964673adb6

Change-Id: I04442eea147c4cbff3e2d51f2c560cd8620d5d55
Signed-off-by: Deren Wu <deren.wu@mediatek.com>
CR-Id: WCNCR00179831
Feature: misc
Reviewed-on: http://gerrit.mediatek.inc:8080/1826098
CheckPatch: Check Patch <srv_checkpatch@mediatek.com>
Reviewed-by: Boforn Lin <boforn.lin@mediatek.com>
Reviewed-by: Chun Lee <chun.lee@mediatek.com>
Reviewed-by: Sarick Jiang <sarick.jiang@mediatek.com>
Build: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Test: srv_mspautosanity@mediatek.com
(cherry picked from commit f0aed3c88bf3e59862fc2bfc5f6aeee34e4cedbf)
Reviewed-on: http://gerrit.mediatek.inc:8080/1830914
CheckCourse: srv_hbgsm001 <srv_hbgsm001@mediatek.com>
Reviewed-by: Eddie Chen <eddie.chen@mediatek.com>
Reviewed-by: Facer Pei <facer.pei@mediatek.com>