[WCNCR00403916] misc: fix -Werror=override-init error by duplicated index in ELEM_ID_MCCAOP_AD_OVERVIEW
[Description]
Fix error by duplicated index in ELEM_ID_MCCAOP_AD_OVERVIEW

May get following error if -Werror=override-init eanbled in gcc
gen4m/mgmt/ie_sort.c:689:31: error: initialized field overwritten
[-Werror=override-init]
  689 |         [ELEM_ID_MCCAOP_AD] = 49,
      |                               ^~

[Rootcause]
ELEM_ID_MCCAOP_AD and ELEM_ID_MCCAOP_AD_OVERVIEW are both defined
as 124. The conflicting index used in the arrays
PROBE_RSP_IE_ORDER[] and BEACON_IE_ORDER[] triggers this build
error by GCC.

[Solution]
In 802.11-2016 Table 9-77, ELEM_ID_MCCAOP_AD_OVERVIEW is defined
as 174. We should update it to the correct index.

MTK-Commit-Id: eefd84af3d8ba7061c77aa2f43b03957b7ae10e2

Fixes: ea31b8f845eb ("[ALPS05574842] wlan: IE sorting")
Change-Id: I66b77d0cf7da090f763a9ef4f31b42b6822afa13
Signed-off-by: Deren Wu <deren.wu@mediatek.com>
CR-Id: WCNCR00403916
Feature: misc
Reviewed-on: https://gerrit.mediatek.inc/c/neptune/wlan_driver/gen4m/+/9828959
Commit-Check: srv_check_service <srv_check_service@mediatek.com>
Reviewed-by: soul.huang <soul.huang@mediatek.com>
Reviewed-by: wyatt.sun <wyatt.sun@mediatek.com>
Coverity-Review-Label: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Build: srv_preflight_b001 <srv_preflight_b001@mediatek.com>
Test: srv_preflight_a001 <srv_preflight_a001@mediatek.com>
Build: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Test: srv_pf_nep_sanity
GAI-Code-Review: srv_ai_review001
AutoUT-Review-Label: srv_neptune_adm <srv_neptune_adm@mediatek.com>
ODB-Check: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Build: srv_preflight_a001 <srv_preflight_a001@mediatek.com>