[ALPS08631203] bypass build error due to mainline migration
[Description]
Bypass build error temporarily.
(Merge tag v6.10-rc1 into android-mainline)

../vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/
linux/gl_wext_priv.c
 error: cast from uint32_t (*)(struct ADAPTER *, void *, uint32_t
, uint32_t *)
(aka unsigned int (*)(struct ADAPTER *, void *, unsigned int,
 unsigned int *))
to PFN_OID_HANDLER_FUNC_REQ
(aka unsigned int (*)(void *, void *, unsigned int, unsigned int
*))
converts to incompatible function type
[-Werror,-Wcast-function-type-strict]
  153 |                 (PFN_OID_HANDLER_FUNC_REQ)

[Test]
Build and Boot up

MTK-Commit-Id: 6347044e2caf3f406c0283741d806b38dc5e5099

Signed-off-by: PoShao Chen <poshao.chen@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: I0119075e45d8315246fde411b1aa56852cfd418b
Reviewed-on: https://gerrit.mediatek.inc/c/neptune/wlan_driver/gen4m/+/9516405
Reviewed-by: johnny.chiang <johnny.chiang@mediatek.com>
Test: srv_preflight_a001 <srv_preflight_a001@mediatek.com>
Build: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Commit-Check: srv_check_service <srv_check_service@mediatek.com>
Reviewed-by: ben.lai <ben.lai@mediatek.com>
Test: srv_pf_nep_sanity
ODB-Check: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Build: srv_preflight_a001 <srv_preflight_a001@mediatek.com>
Build: srv_preflight_b001 <srv_preflight_b001@mediatek.com>
AutoUT-Review-Label: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Coverity-Review-Label: srv_neptune_adm <srv_neptune_adm@mediatek.com>