[ALPS08631203] fix kernel-6.7 build errors
Fix build error according to the follow commits:
66f85d57b710 ("wifi: cfg80211: modify prototype for change_beacon")
bb55441c57cc ("wifi: cfg80211: split struct cfg80211_ap_settings")

Build error:
vendor/mediatek/kernel_modules/connectivity/wlan/core/gen4m/os/linux/gl_init.c:1302:19: error: incompatible function pointer types initializing int (*)(struct wiphy *, struct net_device *, struct cfg80211_ap_update *) with an expression of type int (struct wiphy *, struct net_device *, struct cfg80211_beacon_data *) [-Wincompatible-function-pointer-types]
        .change_beacon = mtk_cfg_change_beacon,

MTK-Commit-Id: ad7f3a85dce45f8d4f26a1c5b657d161a624fb8a

Signed-off-by: Clive Lin <clive.lin@mediatek.com>
CR-Id: ALPS08631203
Feature: Kernel SI Operation
Change-Id: I5915d4d8b31ecfde6b6afa2db6f439dee6cabf9c
Reviewed-on: https://gerrit.mediatek.inc/c/neptune/wlan_driver/gen4m/+/8413543
ODB-Check: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Commit-Check: srv_check_service <srv_check_service@mediatek.com>
CodeQL-Review-Label: srv_pf_nep_win <srv_pf_nep_win@mediatek.com>
Tested-by: johnny.chiang <johnny.chiang@mediatek.com>
Coverity-Review-Label: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Test: srv_pf_nep_sanity
Reviewed-by: boforn.lin <boforn.lin@mediatek.com>
AutoUT-Review-Label: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Reviewed-by: brian-kl.lin <brian-kl.lin@mediatek.com>
Reviewed-by: ben.lai <ben.lai@mediatek.com>
Build: srv_pf_nep_win <srv_pf_nep_win@mediatek.com>
Build: srv_preflight_a001 <srv_preflight_a001@mediatek.com>
Test: srv_preflight_a001 <srv_preflight_a001@mediatek.com>
Build: srv_neptune_adm <srv_neptune_adm@mediatek.com>
Test: srv_mspautosanity
Reviewed-by: johnny.chiang <johnny.chiang@mediatek.com>
Build: srv_preflight_b001 <srv_preflight_b001@mediatek.com>