[WCNCR00147618] misc: Fix build errors with gcc v5.4
[Description]
Fix build errors with gcc v5.4 or "--std=c99":
mgmt/assoc.c:440:154: error: get_current is static but used in
inline function assocComposeReAssocReqFrameHeaderAndFF which is
not static [-Werror]

Tested ok by
1. build 12 variants ok:
    make -f Makefile.x86
       LINUX_SRC={3.10.23/arm, 3.18.42/i386, 4.4.23/amd64, 3.13.11/amd64}
       hif={sdio, pcie, usb}
2. insmod ok on 4.4.39/amd64

MTK-Commit-Id: f6005fa3456686078481ef0fa990a803642a3b1e

Change-Id: I1e39d87b2a139d77035e6d3452d9d2b4576bbcc7
Feature: misc
CR-Id: WCNCR00147618
Signed-off-by: George Kuo <george.kuo@mediatek.com>
(cherry picked from commit 2c37242d762c2dabea64b2bd6e7535d2cbb944ec)