[WCNCR00147618] misc: Fix build errors on linux-3.13.y
[Description]
Fix build errors on linux-3.13.y:
gen4m/os/linux/include/gl_os.h:908:22: error: unknown type name
select_queue_fallback_t
    void *accel_priv, select_queue_fallback_t fallback);
                      ^

Move duplicate lines from wlanSelectQueue() to a new inline function
mtk_wlan_ndev_select_queue() in gl_os.h. Also change return type of
wlanSelectQueue() to u16 to align definitions in struct net_device_ops.

Tested ok by
1. build 12 variants ok:
    make -f Makefile.x86
       LINUX_SRC={3.10.23/arm, 3.18.42/i386, 4.4.23/amd64, 3.13.11/amd64}
       hif={sdio, pcie, usb}
2. insmod ok on 4.4.39/amd64

MTK-Commit-Id: e6ba1eea30d056296a6bc8d25b95d53dae59ce6c

Change-Id: I46a9808bd07c40536720644f630e2cff07db3e9b
Feature: misc
CR-Id: WCNCR00147618
Signed-off-by: George Kuo <george.kuo@mediatek.com>
(cherry picked from commit d54484ebf14ef9d07f69313f858d22b8d5ca1af9)